name: comuline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  chopper: ^8.0.0
  logging: ^1.2.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  pretty_chopper_logger: ^1.2.0
  isar: 
    version: 3.1.7
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: 3.1.7
    hosted: https://pub.isar-community.dev/
  rxdart: ^0.27.7
  bloc_concurrency: ^0.2.5
  alice: ^1.0.0-dev.8
  alice_chopper: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  chopper_generator: ^8.0.0
  json_serializable: ^6.8.0
  isar_generator: 
    version: 3.1.7
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: GeistMono
      fonts: 
        - asset: assets/fonts/GeistMono-Regular.ttf
        - asset: assets/fonts/GeistMono-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
 